In [8]:
import os
import pandas as pd
import time
from google.colab import drive

drive.mount('/content/drive')
%cd /content/drive/MyDrive/Colab Notebooks/Projetos/Funcoes

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/Colab Notebooks/Projetos/Funcoes

In [15]:
%load_ext autoreload
%autoreload 2
import funcoes

import chime
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [4]:
funcoes.try_import('chime')
funcoes.try_import('gspread_formatting','*')

import chime

In [18]:
base = funcoes.read_and_create_feather('files/nubank-2022-02.csv')

Reading files/nubank-2022-02.feather instead

In [10]:
def agrup(group):
  return pd.Series({
      'coluna_soma':group['amount'].sum(),
      'coluna_mean':round(group['amount'].mean(),2),
      'coluna_first':group['amount'].iat[0]
  })
base_groupby = base.groupby(by=['category']).apply(agrup).reset_index()
funcoes.success()
base_groupby

      category  coluna_soma  coluna_mean  coluna_first
0     educação        38.92        19.46         29.02
1  restaurante       182.79       182.79        182.79
2     serviços       160.01        32.00         43.14